### PR TITLE
Fault tolerance for event bus subscription

### PR DESCRIPTION
**Pull request by tsegismont**
See eclipse/vert.x#1848

I couldn't add the FaultToleranceTest since tests in this CM use a mock ZK server

### CODE REVIEW

**Comment by tsegismont** [comment]
Do not merge before eclipse/vert.x#1848

**Comment by tsegismont** [comment]
@stream1984 can you have a look please? Thanks!

**Comment by stream1984** [comment]
@tsegismont LGTM, I will merge it after [vert.x#1848](https://github.com/eclipse/vert.x/pull/1848) be merged, and also try to add some test for it.

**Comment by tsegismont** [comment]
Thank you

2017-03-03 2:57 GMT+01:00 Stream <notifications@github.com>:

**Comment by tsegismont** [comment]
@stream1984 the upstream PR has been merged

**Pull request merged**
