### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by hirik**
zookeeper and Curator version changes

### CODE REVIEW

**Comment by vietj** [comment]
note that curator is used in other places of the stack

**Comment by vietj** [comment]
@stream1984 wdyt ?

**Comment by stream1984** [comment]
For now, zookeeper 3.4.X is major in production, so I keep the version of zookeeper and curator in compatibility.

I also think to refactor vertx-zookeeper in vert.x 4 with zookeeper 3.5.X which using netty4.1.X.

and provide TTL interface to znode.

So with vert.x 3.X  I prefer to zookeeper 3.4.X and curator 2.X.




---------------

Stream Liu 
stream1984@me.com

**Comment by stream-iori** [comment]
see [#90]

**Pull request closed without merging**
